//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///    Класс ресурсов со строгим типом для поиска локализованных строк и пр.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените RESX-файл и снова запустите ResGen
    // с параметром /str или перестройте проект Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedText() {
        }
        
        /// <summary>
        ///    Возврат кэшированного экземпляра ResourceManager, используемого этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LocalizedText", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Переопределяет свойство CurrentUICulture текущего потока для всех
        ///    подстановки ресурсов с помощью этого класса ресурсов со строгим типом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, похожую на Geospace Data Browser, v. 1.0&lt;br&gt;Institute for Radio Astronomy, {0:yyyy}. All rights reserved..
        /// </summary>
        internal static string AboutMessageTemplate {
            get {
                return ResourceManager.GetString("AboutMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, похожую на About.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, похожую на Add.
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, похожую на Geospace Data Browser.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, похожую на Apply.
        /// </summary>
        internal static string ApplyButton {
            get {
                return ResourceManager.GetString("ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, похожую на Data Type:.
        /// </summary>
        internal static string DataTypeLabel {
            get {
                return ResourceManager.GetString("DataTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, похожую на Date:.
        /// </summary>
        internal static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, похожую на Parameter &apos;{0}&apos; has an invalid format..
        /// </summary>
        internal static string ErrorInvalidParameterFormatTemplate {
            get {
                return ResourceManager.GetString("ErrorInvalidParameterFormatTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, похожую на Missing the required parameter &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorMissingRequiredParameterTemplate {
            get {
                return ResourceManager.GetString("ErrorMissingRequiredParameterTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, похожую на From:.
        /// </summary>
        internal static string FromDateLabel {
            get {
                return ResourceManager.GetString("FromDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, похожую на Instrument:.
        /// </summary>
        internal static string InstrumentLabel {
            get {
                return ResourceManager.GetString("InstrumentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, похожую на %Y-%m-%d.
        /// </summary>
        internal static string JsStringDateFormat {
            get {
                return ResourceManager.GetString("JsStringDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, похожую на %Y-%m-%d %H:%i.
        /// </summary>
        internal static string JsStringDateTimeFormat {
            get {
                return ResourceManager.GetString("JsStringDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, похожую на About.
        /// </summary>
        internal static string MenuItemAbout {
            get {
                return ResourceManager.GetString("MenuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, похожую на Constructor.
        /// </summary>
        internal static string MenuItemConstructor {
            get {
                return ResourceManager.GetString("MenuItemConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, похожую на Data.
        /// </summary>
        internal static string MenuItemData {
            get {
                return ResourceManager.GetString("MenuItemData", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, похожую на yyyy-MM-dd.
        /// </summary>
        internal static string NetStringDateFormat {
            get {
                return ResourceManager.GetString("NetStringDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, похожую на yyyy-MM-dd HH:mm.
        /// </summary>
        internal static string NetStringDateTimeFormat {
            get {
                return ResourceManager.GetString("NetStringDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, похожую на Next.
        /// </summary>
        internal static string NextButton {
            get {
                return ResourceManager.GetString("NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованный ресурс типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NoData {
            get {
                object obj = ResourceManager.GetObject("NoData", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, похожую на N/A.
        /// </summary>
        internal static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, похожую на Observatory:.
        /// </summary>
        internal static string ObservatoryLabel {
            get {
                return ResourceManager.GetString("ObservatoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, похожую на Previous.
        /// </summary>
        internal static string PreviousButton {
            get {
                return ResourceManager.GetString("PreviousButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, похожую на Remove.
        /// </summary>
        internal static string RemoveButton {
            get {
                return ResourceManager.GetString("RemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, похожую на To:.
        /// </summary>
        internal static string ToDateLabel {
            get {
                return ResourceManager.GetString("ToDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, похожую на Y From:.
        /// </summary>
        internal static string YRangeFromLabel {
            get {
                return ResourceManager.GetString("YRangeFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, похожую на Y To:.
        /// </summary>
        internal static string YRangeToLabel {
            get {
                return ResourceManager.GetString("YRangeToLabel", resourceCulture);
            }
        }
    }
}
